version: "3.8" #utilizando a versão mais nova do compose

#definindo os serviços que vão ser utilizados => 1.Prometheus 2.Node Exporter 3.PetShop
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" #expõe a porta host:conteiner => 9090 -> 9090 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # monta o yaml no contêiner
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest 
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    #DUVIDA na sintaxe desse volume => perguntar pro lucas
    volumes:
      - '/:/host:ro,rslave'
  petshop:
    image: harbor.sflabs.com.br/processo/petshop:latest
    ports:
      - "3000:3000"
