#configs globais do prometheus
global:
  scrape_interval: "15s"
  scrape_timeout: "10s"

#definido os targets que o prometheus vai coletar os dados => 1.dele mesmo, 2.node exporter 3.petshop
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: node
    static_configs:
      - targets:
          - 192.168.15.11:9100 #TROCAR PARA SEU_IP:9100

  - job_name: petshop_prom
    static_configs:
      - targets:
          - petshop:3000 #aplicação serve as métricas em :3000/metrics